Updated push.yml with the new workflow I disscuss with Dariel and Aviel

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -8,55 +8,54 @@ on:
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
-    
+
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v2
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 11
+      - name: Build image with multi-stage Dockerfile
+        run: docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest .
 
-      - name: Build with Maven
-        run: mvn -B package --file pom.xml
-        
-      - name: Test
-        run: mvn test
-        
-      - name: Increase the Patch part of the jar version
-        run: mvn versions:set -DnewVersion=$(echo $(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) | awk -F. -v OFS=. '{$3++; print}')
-
-      - name: Determine latest tag
-        id: determine_latest_tag
+      - name: Increase image tag
+        id: increase_tag
         run: |
-          git fetch --tags
-          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
-          echo "::set-output name=tag::$TAG"
-
-      - name: Determine Docker image tag
-        id: determine_tag
-        run: |
-          LATEST_TAG=$(echo "${{ steps.determine_latest_tag.outputs.tag }}" | sed 's/v//')
+          LATEST_TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
           TAG="v$(echo "$LATEST_TAG" | awk -F. -v OFS=. '{$3++; print}')"
           echo "::set-output name=tag::$TAG"
 
-      - name: Login to DockerHub
+      - name: Test image
+        run: |
+          # Run your image test commands here
+          # If the tests fail, delete the new tag
+          if [[ tests_failed ]]; then
+            git tag -d ${{ steps.increase_tag.outputs.tag }}
+            git push origin :refs/tags/${{ steps.increase_tag.outputs.tag }}
+            echo "Image tests failed. Deleted the new tag."
+            exit 1
+          fi
+
+      - name: Increase pom.xml version
+        run: mvn versions:set -DnewVersion=$(echo $(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) | awk -F. -v OFS=. '{$3++; print}')
+
+      - name: Push pom.xml
+        run: |
+          git config user.name "or-carmeli"
+          git config user.email "ocarmeli7@gmail.com"
+          git add pom.xml
+          git commit -m "Increase pom.xml version"
+          git push origin development
+
+      - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          push: true
-          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ steps.determine_tag.outputs.tag }}
-          latest-tag: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest
+      - name: Push image
+        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ steps.increase_tag.outputs.tag }}
 
-
-      - name: Create PR
+      - name: Create Pull Request
         uses: repo-sync/pull-request@v2
         with:
-          destination_branch: "master"  
+          destination_branch: "master"
           github_token: ${{ secrets.GITHUB_TOKEN }}
